server:
  tomcat:
    max-http-form-post-size: 10MB
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: dev
    include:
      - oauth
      - jwt
      - s3
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # myEmail -> my_email
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: 1234
logging.level:
  org.hibernate.SQL: trace

---

spring:
  config.activate.on-profile: prod

---

spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://${LOCAL_IP}:${MYSQL_LOCAL_PORT}/${MYSQL_LOCAL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_LOCAL_USER}
    password: ${MYSQL_LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
